move bundle decoding functions to the bundle
This makes the runtime more generic
and allows future bundle formats.

The C bundles can also be encrypted to prevent unintended modifications

diff --git a/tools/luaxc.sh.in b/tools/luaxc.sh.in
--- a/tools/luaxc.sh.in
+++ b/tools/luaxc.sh.in
@@ -77,6 +77,7 @@ case "$1" in
 esac
 
 BYTECODE=@BYTECODE
+CRYPT=
 TARGET=
 OUTPUT=
 SOURCES=()
@@ -86,19 +87,20 @@ VERBOSE=true
 while [ -n "$1" ]
 do
     case "$1" in
-        (-b)    BYTECODE="-b"; shift ;;
-        (-s)    BYTECODE="-s"; shift ;;
-        (-o)    OUTPUT="$2"; shift 2 ;;
-        (-t)    TARGET="$2"; shift 2 ;;
-        (-p)    PREFIX="$2"; shift 2 ;;
-        (-q)    VERBOSE=false; shift ;;
-        (-h)    usage ;;
-        (*)     if ! [ -f "$1" ]
-                then
-                    echo "$1: file not found" >&2
-                    exit 1
-                fi
-                SOURCES+=("$1"); shift ;;
+        (-b)        BYTECODE="-b"; shift ;;
+        (-s)        BYTECODE="-s"; shift ;;
+        (-crypt)    CRYPT="-crypt"; shift ;;
+        (-o)        OUTPUT="$2"; shift 2 ;;
+        (-t)        TARGET="$2"; shift 2 ;;
+        (-p)        PREFIX="$2"; shift 2 ;;
+        (-q)        VERBOSE=false; shift ;;
+        (-h)        usage ;;
+        (*)         if ! [ -f "$1" ]
+                    then
+                        echo "$1: file not found" >&2
+                        exit 1
+                    fi
+                    SOURCES+=("$1"); shift ;;
     esac
 done
 
@@ -253,7 +255,7 @@ then
     echo "sources: ${SOURCES[*]}"
 fi
 
-luax "$LUAXC_DIR/luax_bundle.lua" -app $BYTECODE -c -name="$OUTPUT" "${SOURCES[@]}" > "$TMP/app_bundle.c"
+luax "$LUAXC_DIR/luax_bundle.lua" -app $BYTECODE -c $CRYPT -name="$OUTPUT" "${SOURCES[@]}" > "$TMP/app_bundle.c"
 zig cc "${ZIG_OPT[@]}" "${LIBS[@]}" "$TMP/app_bundle.c" -o "$OUTPUT"
 
 exit # ------------------------------8<------------------------------
